export const gameList: { title: string; targetScore: number }[] = [
  { title: "THUNDER", targetScore: 36 },
  { title: "PIN CLIMB", targetScore: 140 },
  { title: "LLAND", targetScore: 3 },
  { title: "IN TOW", targetScore: 10 },
  { title: "BALL TOUR", targetScore: 9 },
  { title: "BASERUNNER DASH", targetScore: 2 },
  { title: "UP 1 WAY", targetScore: 2 },
  { title: "BOX SNAKE", targetScore: 50 },
  { title: "UP SHOT", targetScore: 100 },
  { title: "GRAPPLING H", targetScore: 20 },
  { title: "CYWALL", targetScore: 150 },
  { title: "PAKU PAKU", targetScore: 60 },
  { title: "STOMPING BUBBLES", targetScore: 250 },
  { title: "WAVY BIRD", targetScore: 50 },
  { title: "VINE CLIMBER", targetScore: 2 },
  { title: "SUNFLOWER SWAY", targetScore: 100 },
  { title: "ROTATION ROD", targetScore: 150 },
  { title: "STAGE SEPARATION", targetScore: 120 },
  { title: "CATCHING WHEEL", targetScore: 20 },
  { title: "SLIME STRETCHER", targetScore: 22 },
  { title: "JUGGLING ACT", targetScore: 7 },
  { title: "WINDOW WASHER", targetScore: 10 },
  { title: "TWIN JUMPERS", targetScore: 80 },
  { title: "ELASTIC HERO", targetScore: 1 },
  { title: "BLADE DANCER", targetScore: 10 },
  { title: "WIND POWER", targetScore: 100 },
  { title: "SKY RAFTSMAN", targetScore: 80 },
  { title: "GRAVITY WELL", targetScore: 60 },
  { title: "PULSE PIPER", targetScore: 50 },
  { title: "FALL BOUNCE", targetScore: 100 },
  { title: "LIGHT DARK", targetScore: 120 },
  { title: "FROOOOG", targetScore: 50 },
  { title: "REFLECTOR", targetScore: 10 },
  { title: "SHINY", targetScore: 1 },
  { title: "FLIP O", targetScore: 5 },
  { title: "TIMBER TEST", targetScore: 100 },
  { title: "SURVIVOR", targetScore: 9 },
  { title: "GROWTH", targetScore: 1000 },
  { title: "REBIRTH", targetScore: 2 },
  { title: "CAST N", targetScore: 12 },
  { title: "NUMBER BALL", targetScore: 9 },
  { title: "ORBIT MAN", targetScore: 20 },
  { title: "TAPE J", targetScore: 300 },
  { title: "BAMBOO", targetScore: 100 },
  { title: "DESCENT S", targetScore: 100 },
  { title: "R WHEEL", targetScore: 25 },
  { title: "SCRAMBIRD", targetScore: 10 },
  { title: "CLEAN ROBO", targetScore: 5 },
  { title: "FRACAVE", targetScore: 5 },
  { title: "FISH GRILL", targetScore: 30 },
  { title: "MONKEY T", targetScore: 8 },
  { title: "JUMP ON", targetScore: 30 },
  { title: "LEVITATION", targetScore: 20 },
  { title: "G PRESS", targetScore: 70 },
  { title: "SQUARE BAR", targetScore: 5 },
  { title: "TURBULENT", targetScore: 100 },
  { title: "CATE P", targetScore: 5 },
  { title: "GEOCENT", targetScore: 1 },
  { title: "HEXMIN", targetScore: 25 },
  { title: "LADDER DROP", targetScore: 1 },
  { title: "ARCFIRE", targetScore: 10 },
  { title: "SLALOM", targetScore: 20 },
  { title: "CLOCK TURRET", targetScore: 5 },
  { title: "METEO PLANET", targetScore: 16 },
  { title: "ROLL HOLD", targetScore: 50 },
  { title: "FOOT LASER", targetScore: 30 },
  { title: "LASER FORTRESS", targetScore: 100 },
  { title: "PIZZA ARROW", targetScore: 200 },
  { title: "ACCEL B", targetScore: 10 },
  { title: "UP DOWN PRESS", targetScore: 5 },
  { title: "COUNTER B", targetScore: 3 },
  { title: "M RIDER", targetScore: 10 },
  { title: "S SHAKE", targetScore: 10 },
  { title: "ZONE B", targetScore: 1 },
  { title: "M JAMMING", targetScore: 50 },
  { title: "FLIPBOMB", targetScore: 20 },
  { title: "D LASER", targetScore: 50 },
  { title: "GRENADIER", targetScore: 50 },
  { title: "KITE", targetScore: 500 },
  { title: "CATAPULT", targetScore: 30 },
  { title: "HOLES", targetScore: 300 },
  { title: "NS CLIMB", targetScore: 500 },
  { title: "SNAKY", targetScore: 15 },
  { title: "MIRROR FLOOR", targetScore: 4 },
  { title: "SUB JUMP", targetScore: 10 },
  { title: "ROLL S", targetScore: 7 },
  { title: "T PUNCH", targetScore: 100 },
  { title: "MORTAR", targetScore: 25 },
  { title: "GRAVELER", targetScore: 30 },
  { title: "THROW M", targetScore: 8 },
  { title: "AERIAL BAR", targetScore: 100 },
  { title: "SCAFFOLD", targetScore: 2 },
  { title: "BS FISH", targetScore: 100 },
  { title: "NUMBER LINE", targetScore: 10 },
  { title: "D MISSILE", targetScore: 10 },
  { title: "D PISTOLS", targetScore: 50 },
  { title: "UD CAVE", targetScore: 80 },
  { title: "SLASHES", targetScore: 100 },
  { title: "UNCTRL", targetScore: 50 },
  { title: "CIRCLE W", targetScore: 2500 },
  { title: "TWO FACED", targetScore: 5 },
  { title: "TR BEAM", targetScore: 50 },
  { title: "BOARDING", targetScore: 30 },
  { title: "SWINGBY", targetScore: 300 },
  { title: "M FIELD", targetScore: 20 },
  { title: "PARKING", targetScore: 100 },
  { title: "EAROCK", targetScore: 1 },
  { title: "TAPPUMP", targetScore: 300 },
  { title: "SNAKE 1", targetScore: 2 },
  { title: "FLOORS 5", targetScore: 400 },
  { title: "LIFT UP", targetScore: 15 },
];
