export const gameList: { title: string; targetScore: number }[] = [
  { title: "THUNDER", targetScore: 36 },
  { title: "PIN CLIMB", targetScore: 150 },
  { title: "LLAND", targetScore: 3 },
  { title: "IN TOW", targetScore: 10 },
  { title: "BALL TOUR", targetScore: 9 },
  { title: "BASERUNNER DASH", targetScore: 2 },
  { title: "UP 1 WAY", targetScore: 2 },
  { title: "BOX SNAKE", targetScore: 50 },
  { title: "UP SHOT", targetScore: 100 },
  { title: "GRAPPLING H", targetScore: 25 },
  { title: "CYWALL", targetScore: 150 },
  { title: "PAKU PAKU", targetScore: 60 },
  { title: "STOMPING BUBBLES", targetScore: 250 },
  { title: "WAVY BIRD", targetScore: 50 },
  { title: "VINE CLIMBER", targetScore: 2 },
  { title: "SUNFLOWER SWAY", targetScore: 100 },
  { title: "ROTATION ROD", targetScore: 150 },
  { title: "STAGE SEPARATION", targetScore: 160 },
  { title: "CATCHING WHEEL", targetScore: 20 },
  { title: "SLIME STRETCHER", targetScore: 22 },
];
